version: '3.8'

services:
    maplio-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: maplio-api-server
        network_mode: host
        restart: always
        environment:
            - API_KEY=${API_KEY}
            - CORS_ORIGIN=${CORS_ORIGIN}
